version: '3.7'
services:
    web:
        build:
            args:
                APP_ENV: production
        restart: always
        volumes:
            - ./public:/var/www/html/public

    nginx:
        restart: always
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./public:/var/www/html/public
