version: '3.7'
services:
    web:
        build:
            args:
                APP_ENV: production
        restart: always
        volumes:
            - ./public:/var/www/html/public

    nginx:
        restart: always
        command: sh -c "sed 's/{{NGINX_HOST}}/hackdawg.com/g' /etc/nginx/conf.d/hackdawg.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./deploy/nginx/hackdawg.template:/etc/nginx/conf.d/hackdawg.template
            - ./public:/var/www/html/public
