version: '3.7'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: web
        image: hackdawg-web
        depends_on:
            - db
        links:
            - db
        working_dir: /var/www/html
        networks:
            - app
        env_file:
            - .env

    scheduler:
        container_name: scheduler
        image: hackdawg-web
        depends_on:
            - web
        command: hackdawg-scheduler
        networks:
            - app
        env_file:
            - .env

    queuer:
        container_name: queuer
        image: hackdawg-web
        depends_on:
            - web
        command: hackdawg-queuer
        networks:
            - app
        env_file:
            - .env

    nginx:
        container_name: nginx
        build:
            context: .
            dockerfile: nginx.Dockerfile
        depends_on:
            - web
        networks:
            - app
        env_file:
            - .env

    db:
        container_name: db
        image: mysql:5.7
        networks:
            - app

networks:
    app:
