version: '3.7'
services:
    web:
        build:
            args:
                APP_ENV: local
        restart: unless-stopped
        volumes:
            - ..:/var/www/html
            - ./php.ini:/usr/local/etc/php/conf.d/local.ini

    scheduler:
        volumes:
            - ..:/var/www/html

    queuer:
        volumes:
            - ..:/var/www/html

    nginx:
        restart: unless-stopped
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ..:/var/www/html:ro
        environment:
            DOMAIN: local.hackdawg.com
            EMAIL: hello@hackdawg.com

    db:
        restart: unless-stopped
        volumes:
            - ./db/data:/var/lib/mysql
        ports:
            - '33069:3306'
        environment:
            MYSQL_DATABASE: hackdawg
            MYSQL_USER: hackdawg
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
