version: '3.7'
services:
    web:
        build:
            context: ..
            dockerfile: deploy/Dockerfile
        container_name: web
        image: hackdawg-web
        depends_on:
            - db
        links:
            - db
        working_dir: /var/www/html
        networks:
            - app

    scheduler:
        container_name: scheduler
        image: hackdawg-web
        depends_on:
            - web
        command: hackdawg-scheduler
        networks:
            - app

    queuer:
        container_name: queuer
        image: hackdawg-web
        depends_on:
            - web
        command: hackdawg-queuer
        networks:
            - app

    nginx:
        container_name: nginx
        image: nginx:alpine
        depends_on:
            - web
        working_dir: /var/www/html
        networks:
            - app

    db:
        container_name: db
        image: mysql:5.7
        networks:
            - app

networks:
    app:
