version: '3.7'
services:
    web:
        build:
            args:
                APP_ENV: local
        restart: unless-stopped
        volumes:
            - ..:/var/www/html
            - ./php.ini:/usr/local/etc/php/conf.d/local.ini

    nginx:
        restart: unless-stopped
        command: sh -c "sed 's/{{NGINX_HOST}}/hackdawg.test/g' /etc/nginx/conf.d/nginx.conf.tmpl > /etc/nginx/conf.d/nginx.conf && exec nginx -g 'daemon off;'"
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ..:/var/www/html:ro
            - ./nginx/nginx.conf.tmpl:/etc/nginx/conf.d/nginx.conf.tmpl

    db:
        restart: unless-stopped
        volumes:
            - ./db/data:/var/lib/mysql
        ports:
            - '33069:3306'
        environment:
            MYSQL_DATABASE: hackdawg
            MYSQL_USER: hackdawg
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
