version: '3.7'
services:
    web:
        build:
            args:
                APP_ENV: local
        restart: unless-stopped
        volumes:
            - ..:/var/www/html
            - ./php.ini:/usr/local/etc/php/conf.d/local.ini

    scheduler:
        restart: unless-stopped
        volumes:
            - ..:/var/www/html

    queuer:
        restart: unless-stopped
        volumes:
            - ..:/var/www/html

    nginx:
        restart: unless-stopped
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ..:/var/www/html
        environment:
            DOMAIN: hackdawg.test
            EMAIL: hello@hackdawg.com

    db:
        restart: unless-stopped
        ports:
            - '33069:3306'
        volumes:
            - ./db/data:/var/lib/mysql
        env_file:
          - ../.env
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

    redis:
        restart: unless-stopped
        ports:
            - '6379:6379'
        volumes:
            - ./redis/data:/var/lib/redis
