version: '3.7'
services:
    web:
        build:
            args:
                APP_ENV: production
        restart: always

    scheduler:
        restart: always

    queuer:
        restart: always

    nginx:
        restart: always
        ports:
            - '80:80'
            - '443:443'
        environment:
            DOMAIN: hackdawg.com
            EMAIL: hello@hackdawg.com

    redis:
        restart: always
        ports:
            - '6379:6379'
        volumes:
            - ./redis/data:/var/lib/redis
