version: '3.7'
services:
  web:
    build:
      args:
        APP_ENV: testing
    restart: always
    env_file:
      - ../.env

  nginx:
    restart: always
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAIN: hackdawg.test
      EMAIL: hello@hackdawg.com

  db:
    restart: unless-stopped
    ports:
      - '33069:3306'
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - ../.env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

volumes:
  db_data:
