version: '3.7'
services:
    web:
        build:
            args:
                APP_ENV: production
        restart: always
        volumes:
            - /var/www/html/storage

    nginx:
        restart: always
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - /var/www/html/storage
        environment:
            DOMAIN: hackdawg.com
            EMAIL: hello@hackdawg.com
