version: '3.7'
services:
    web:
        build:
            args:
                APP_ENV: production
        restart: always
        env_file:
          - ../.env

    scheduler:
        restart: always

    queuer:
        restart: always

    nginx:
        restart: always
        ports:
            - '80:80'
            - '443:443'
        environment:
            DOMAIN: hackdawg.com
            EMAIL: hello@hackdawg.com

    db:
        restart: unless-stopped
        ports:
            - '33069:3306'
        volumes:
            - ./db/data:/var/lib/mysql
        env_file:
          - ../.env
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

    redis:
        restart: always
        ports:
            - '6379:6379'
        volumes:
            - ./redis/data:/var/lib/redis
