name: Deploy

on:
  push:
    branches:
      - master

jobs:
  Build-Test-Deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: hackdawg
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.4'
          extensions: curl, mbstring, openssl, pdo, mysql, xml
          coverage: none

      - name: Copy environment file
        run: cp ./deploy/secrets/.env.testing .env.testing

      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Build frontend
        run: |
          yarn install
          yarn prod

      - name: Execute tests
        run: |
          composer test
          yarn test
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: SECRET_PASSPHRASE=${{ secrets.SECRET_PASSPHRASE }} /root/hackdawg.com/deploy/deploy.sh
