name: Run tests

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master

jobs:
  Build-Test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Build
        run: |
          # Install linux utilities
          sudo apt-get update -y
          sudo apt-get install -y make

          # Copy environment file
          cp ./deploy/secrets/.env.testing .env

          # Here we go...
          make deploy@testing
#          make chore@testing

      - name: Test
        run: |
          composer test
          yarn test
