name: Run tests

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master

jobs:
  Build-Test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Build
        run: |
          # Install linux utilities
          apt-get update -y
          apt-get install -y make

          # Here we go...
          make deploy@local
          make chore@local

      - name: Test
        run: |
          composer test
          yarn test
