name: Upload Assets

on:
  push:
    branches:
      - feat/deployment
      - master
    paths:
    - 'resources/**'
    - '!resources/lang/**'

jobs:
    Build-Upload:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [12.x]

      steps:
        - name: Checkout repository
          uses: actions/checkout@v1

        - name: Build
          run: |
            yarn install
            yarn prod
        
        - name: Upload
          uses: appleboy/scp-action@master
          with:
            host: 206.189.85.59
            username: root
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            source: "public/css,public/js,public/mix-manifest.json"
            target: "/root/hackdawg.com"